name: Build, Test, and Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets and vars
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "BREWFATHER_USERID=${{ secrets.BREWFATHER_USERID }}" >> .env
          echo "BREWFATHER_API_KEY=${{ secrets.BREWFATHER_API_KEY }}" >> .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "FRONTEND_ORIGIN=${{ vars.FRONTEND_ORIGIN }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint || echo 'Lint errors ignored for CI'
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Archive production artifacts
        if: success()
        run: |
          mkdir -p artifact
          cp -r * artifact/
        shell: bash
        # Optionally use actions/upload-artifact if you want to pass to another job

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets and vars
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "BREWFATHER_USERID=${{ secrets.BREWFATHER_USERID }}" >> .env
          echo "BREWFATHER_API_KEY=${{ secrets.BREWFATHER_API_KEY }}" >> .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "FRONTEND_ORIGIN=${{ vars.FRONTEND_ORIGIN }}" >> .env

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --exclude node_modules --exclude .git ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}

      - name: Install dependencies and restart app on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ${{ secrets.EC2_PATH }} &&
            npm install &&
            pm2 restart index.js || pm2 start index.js --name kammryndancyAPI
          '
