name: Build, Test, and Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets and vars
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "BREWFATHER_USERID=${{ secrets.BREWFATHER_USERID }}" >> .env
          echo "BREWFATHER_API_KEY=${{ secrets.BREWFATHER_API_KEY }}" >> .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "FRONTEND_ORIGIN=${{ vars.FRONTEND_ORIGIN }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint || echo 'Lint errors ignored for CI'
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Archive production artifacts
        if: success()
        run: |
          mkdir -p artifact
          rsync -av --exclude artifact ./ artifact/
        shell: bash

      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-artifact
          path: artifact/

  deploy:
    needs: build-test
    runs-on: self-hosted
    environment: production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-artifact
          path: artifact/

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets and vars
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "BREWFATHER_USERID=${{ secrets.BREWFATHER_USERID }}" >> .env
          echo "BREWFATHER_API_KEY=${{ secrets.BREWFATHER_API_KEY }}" >> .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "FRONTEND_ORIGIN=${{ vars.FRONTEND_ORIGIN }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Restart app with PM2
        run: |
          pm2 restart index.js || pm2 start index.js --name kammryndancyAPI
